// Copyright (c) 2022 TrakHound Inc., All Rights Reserved.

// This file is subject to the terms and conditions defined in
// file 'LICENSE.txt', which is part of this source code package.

namespace MTConnect.Streams.Samples
{
    /// <summary>
    /// The value of Wattage used or generated by a component over an interval of time.
    /// </summary>
    public class ElectricalEnergyValue : SampleValue
    {
        protected override double MetricConversion => 1;
        protected override double InchConversion => 1;
        protected override string MetricUnits => "WATT_SECOND";
        protected override string InchUnits => "WATT_SECOND";


        public ElectricalEnergyValue(double energy, UnitSystem unitSystem = UnitSystem.METRIC)
        {
            Value = energy;
            UnitSystem = unitSystem;
        }
    }
}
