// Copyright (c) 2026 TrakHound Inc., All Rights Reserved.
// TrakHound Inc. licenses this file to you under the MIT license.

using System.Linq;
using MTConnect.Agents;
using MTConnect.Devices;
using MTConnect.Devices.DataItems;
using NUnit.Framework;

namespace MTConnect.Tests.Common.Agents
{
    /// <summary>
    /// Asserts that the auto-injected ASSET_COUNT DataItem carries the
    /// MTConnect-mandated DATA_SET representation.
    ///
    /// MTConnect Standard, Part 2 — Devices Information Model, defines
    /// ASSET_COUNT (UML element ID
    /// _19_0_3_68e0225_1640602520420_217627_44, also captured in
    /// AssetCountDataItem.g.cs) as a DATA_SET representation: a map of
    /// asset-type to the count of assets of that type currently held in
    /// the agent's asset buffer. The agent auto-injects an
    /// AssetCountDataItem when normalising a device, and that injection
    /// must produce a DataItem whose Representation is DATA_SET so the
    /// resulting Probe matches the spec.
    /// </summary>
    [TestFixture]
    [Category("AssetCountIsDataSet")]
    public class AssetCountAutoGeneratedDataSetTests
    {
        [Test]
        public void AutoInjected_AssetCount_Has_DataSet_Representation()
        {
            using var agent = new MTConnectAgent(initializeAgentDevice: false);

            var device = new Device
            {
                Id = "dev",
                Name = "dev",
                Uuid = "dev-uuid"
            };

            var added = agent.AddDevice(device, initializeDataItems: false);

            Assert.That(added, Is.Not.Null);

            var assetCount = added.DataItems
                .SingleOrDefault(d => d.Type == AssetCountDataItem.TypeId);

            Assert.That(assetCount, Is.Not.Null,
                "auto-generator must inject one ASSET_COUNT DataItem");
            Assert.That(assetCount!.Representation,
                Is.EqualTo(DataItemRepresentation.DATA_SET),
                "auto-injected ASSET_COUNT must carry DATA_SET representation per MTConnect Part 2");
        }

        [Test]
        public void UserDeclared_AssetCount_Representation_Is_Preserved()
        {
            using var agent = new MTConnectAgent(initializeAgentDevice: false);

            var declared = new AssetCountDataItem("dev")
            {
                Representation = DataItemRepresentation.VALUE
            };

            var device = new Device
            {
                Id = "dev",
                Name = "dev",
                Uuid = "dev-uuid",
                DataItems = new[] { declared }
            };

            var added = agent.AddDevice(device, initializeDataItems: false);

            Assert.That(added, Is.Not.Null);

            var assetCount = added.DataItems
                .SingleOrDefault(d => d.Type == AssetCountDataItem.TypeId);

            Assert.That(assetCount, Is.Not.Null);
            Assert.That(assetCount!.Representation,
                Is.EqualTo(DataItemRepresentation.VALUE),
                "user-declared ASSET_COUNT representation must be preserved verbatim");
        }
    }
}
