// Copyright (c) 2024 TrakHound Inc., All Rights Reserved.
// TrakHound Inc. licenses this file to you under the MIT license.

using MTConnect.Input;
using MTConnect.Observations;
using System;
using System.Text.RegularExpressions;

namespace MTConnect.Shdr
{
    /// <summary>
    /// A FaultState associated with an MTConnect Condition Observation
    /// </summary>
    public class ShdrFaultState : ObservationInput
    {
        private static readonly Regex _deviceKeyRegex = new Regex("(.*):(.*)");


        /// <summary>
        /// Level of the Condition (Normal, Warning, Fault, or Unavailable)
        /// </summary>
        public ConditionLevel Level
        {
            get => GetValue(ValueKeys.Level).ConvertEnum<ConditionLevel>();
            set => AddValue(new ObservationValue(ValueKeys.Level, value));
        }

        /// <summary>
        /// Identifier of an individual condition activation provided by a piece of equipment.
        /// </summary>
        public string ConditionId
        {
            get => GetValue(ValueKeys.ConditionId);
            set
            {
                var val = !string.IsNullOrEmpty(value) ? value : null;
                AddValue(new ObservationValue(ValueKeys.ConditionId, val));
            }
        }

        /// <summary>
        /// The native code (usually an alpha-numeric value) generated by the controller of a piece of equipment providing a reference identifier for a condition state or alarm.
        /// This is the same information an operator or maintenance personnel would see as a reference code designating a specific type of Condition when viewed at the piece of equipment.Usually this reference code is used to point to a more detailed description of the Condition.
        /// </summary>
        public string NativeCode
        {
            get => GetValue(ValueKeys.NativeCode);
            set
            {
                var val = !string.IsNullOrEmpty(value) ? value : null;
                AddValue(new ObservationValue(ValueKeys.NativeCode, val));
            }
        }

        /// <summary>
        /// If the data source assigns a severity level to a Condition, nativeSeverity is used to report that severity information to a client software application.
        /// </summary>
        public string NativeSeverity
        {
            get => GetValue(ValueKeys.NativeSeverity);
            set
            {
                var val = !string.IsNullOrEmpty(value) ? value : null;
                AddValue(new ObservationValue(ValueKeys.NativeSeverity, val));
            }
        }

        /// <summary>
        /// Qualifies the Condition and adds context or additional clarification.
        /// This optional attribute can be used to convey information such as HIGH or LOW type Warning and Fault condition to indicate differing types of condition states
        /// </summary>
        public ConditionQualifier Qualifier
        {
            get => GetValue(ValueKeys.Qualifier).ConvertEnum<ConditionQualifier>();
            set
            {
                if (value != ConditionQualifier.NOT_SPECIFIED)
                {
                    AddValue(new ObservationValue(ValueKeys.Qualifier, value));
                }
            }
        }

        /// <summary>
        /// The Message of the Condition Observation
        /// </summary>
        public string Message
        {
            get => GetValue(ValueKeys.Message);
            set
            {
                var val = !string.IsNullOrEmpty(value) ? value : null;
                AddValue(new ObservationValue(ValueKeys.Message, val));
            }
        }

        /// <summary>
        /// Flag to set whether the Observation has been sent by the adapter or not
        /// </summary>
        internal bool IsSent { get; set; }


        public ShdrFaultState() { }

        public ShdrFaultState(
            ConditionLevel level,
            string message = null,
            string nativeCode = null,
            string nativeSeverity = null,
            ConditionQualifier qualifier = ConditionQualifier.NOT_SPECIFIED,
            string conditionId = null
            )
        {
            Level = level;
            if (!string.IsNullOrEmpty(nativeCode)) ConditionId = conditionId;
            if (!string.IsNullOrEmpty(nativeCode)) NativeCode = nativeCode;
            if (!string.IsNullOrEmpty(nativeSeverity)) NativeSeverity = nativeSeverity;
            Qualifier = qualifier;
            if (!string.IsNullOrEmpty(message)) Message = message;
        }

        public ShdrFaultState(
            long timestamp,
            ConditionLevel level,
            string message = null,
            string nativeCode = null,
            string nativeSeverity = null,
            ConditionQualifier qualifier = ConditionQualifier.NOT_SPECIFIED,
            string conditionId = null
            )
        {
            Level = level;
            if (!string.IsNullOrEmpty(nativeCode)) ConditionId = conditionId;
            if (!string.IsNullOrEmpty(nativeCode)) NativeCode = nativeCode;
            if (!string.IsNullOrEmpty(nativeSeverity)) NativeSeverity = nativeSeverity;
            Qualifier = qualifier;
            if (!string.IsNullOrEmpty(message)) Message = message;
            Timestamp = timestamp;
        }

        public ShdrFaultState(
            DateTime timestamp,
            ConditionLevel level,
            string message = null,
            string nativeCode = null,
            string nativeSeverity = null,
            ConditionQualifier qualifier = ConditionQualifier.NOT_SPECIFIED,
            string conditionId = null
            )
        {
            Level = level;
            if (!string.IsNullOrEmpty(nativeCode)) ConditionId = conditionId;
            if (!string.IsNullOrEmpty(nativeCode)) NativeCode = nativeCode;
            if (!string.IsNullOrEmpty(nativeSeverity)) NativeSeverity = nativeSeverity;
            Qualifier = qualifier;
            if (!string.IsNullOrEmpty(message)) Message = message;
            Timestamp = timestamp.ToUnixTime();
        }

        public ShdrFaultState(IConditionFaultStateObservationInput conditionObservation)
        {
            if (conditionObservation != null)
            {
                DeviceKey = conditionObservation.DeviceKey;
                DataItemKey = conditionObservation.DataItemKey;
                Level = conditionObservation.Level;
                if (!string.IsNullOrEmpty(conditionObservation.ConditionId)) ConditionId = conditionObservation.ConditionId;
                if (!string.IsNullOrEmpty(conditionObservation.NativeCode)) NativeCode = conditionObservation.NativeCode;
                if (!string.IsNullOrEmpty(conditionObservation.NativeSeverity)) NativeSeverity = conditionObservation.NativeSeverity;
                Qualifier = conditionObservation.Qualifier;
                if (!string.IsNullOrEmpty(conditionObservation.Message)) Message = conditionObservation.Message;
                Timestamp = conditionObservation.Timestamp;
            }
        }


        /// <summary>
        /// Convert ShdrFaultState to an SHDR string
        /// </summary>
        /// <returns>SHDR string</returns>
        public override string ToString()
        {
            if (!string.IsNullOrEmpty(DataItemKey))
            {
                var target = DataItemKey;
                if (!string.IsNullOrEmpty(DeviceKey)) target = $"{DeviceKey}:{target}";

                
                string identifier;
                if (!string.IsNullOrEmpty(NativeCode))
                {
                    identifier = !string.IsNullOrEmpty(ConditionId) ? $"{NativeCode}:{ConditionId}" : NativeCode;
                }
                else
                {
                    identifier = ConditionId;
                }

                // If no ConditionId or NativeCode specified, then create hash of Message
                if (string.IsNullOrEmpty(identifier)) identifier = Message?.ToMD5Hash();
                
                var message = !string.IsNullOrEmpty(Message) ? Message.Replace("|", @"\|") : "";
                var qualifier = Qualifier != ConditionQualifier.NOT_SPECIFIED ? Qualifier.ToString() : "";

                string line;

                if (Timestamp > 0)
                {
                    if (Level != ConditionLevel.UNAVAILABLE)
                    {
                        line = $"{Timestamp.ToDateTime().ToString("o")}|{target}|{Level}|{identifier}|{NativeSeverity}|{qualifier}|{message}";
                    }
                    else
                    {
                        line = $"{Timestamp.ToDateTime().ToString("o")}|{target}|{Level}||||";
                    }
                }
                else
                {
                    if (Level != ConditionLevel.UNAVAILABLE)
                    {
                        line = $"|{target}|{Level}|{identifier}|{NativeSeverity}|{qualifier}|{message}";
                    }
                    else
                    {
                        line = $"|{target}|{Level}||||";
                    }
                }

                return line;
            }

            return "";
        }


        /// <summary>
        /// Read a ShdrCondition object from an SHDR line
        /// </summary>
        /// <param name="input">SHDR Input String</param>
        public static ShdrFaultState FromString(string input)
        {
            if (!string.IsNullOrEmpty(input))
            {
                // Expected format : <timestamp>|<data_item_name>|<level>|<native_code>|<native_severity>|<qualifier>|<message>
                // Expected format : 2014-09-29T23:59:33.460470Z|htemp|WARNING|HTEMP|1|HIGH|Oil Temperature High

                // Start reading input and read Timestamp first (if specified)
                var x = ShdrLine.GetNextValue(input);

                if (!string.IsNullOrEmpty(x))
                {
                    if (DateTime.TryParse(x, null, System.Globalization.DateTimeStyles.AdjustToUniversal, out var timestamp))
                    {
                        var y = ShdrLine.GetNextSegment(input);
                        return FromLine(y, timestamp.ToUnixTime());
                    }
                }
                else
                {
                    var y = ShdrLine.GetNextSegment(input);
                    return FromLine(y);
                }
            }

            return null;
        }

        private static ShdrFaultState FromLine(string input, long timestamp = 0)
        {
            if (!string.IsNullOrEmpty(input))
            {
                try
                {
                    var condition = new ShdrFaultState();
                    condition.Timestamp = timestamp;

                    // Set DataItemKey
                    var x = ShdrLine.GetNextValue(input);
                    var y = ShdrLine.GetNextSegment(input);

                    // Get Device Key (if specified). Example : Device01:avail
                    var match = _deviceKeyRegex.Match(x);
                    if (match.Success && match.Groups.Count > 2)
                    {
                        condition.DeviceKey = match.Groups[1].Value;
                        condition.DataItemKey = match.Groups[2].Value;
                    }
                    else
                    {
                        condition.DataItemKey = x;
                    }

                    // Set Condition Level
                    x = ShdrLine.GetNextValue(y);
                    y = ShdrLine.GetNextSegment(y);
                    condition.Level = (ConditionLevel)Enum.Parse(typeof(ConditionLevel), x);

                    if (y != null)
                    {
                        string identifier = null;

                        // Set NativeCode
                        x = ShdrLine.GetNextValue(y);
                        y = ShdrLine.GetNextSegment(y);
                        if (!string.IsNullOrEmpty(x)) identifier = x;

                        if (identifier != null)
                        {
                            var i = identifier.IndexOf(':');
                            if (i > 0 && i + 1 < identifier.Length)
                            {
                                condition.NativeCode = identifier.Substring(0, i);
                                condition.ConditionId = identifier.Substring(i + 1);
                            }
                            else
                            {
                                condition.NativeCode = identifier;
                                condition.ConditionId = identifier;
                            }
                        }

                        if (y != null)
                        {
                            // Set NativeSeverity
                            x = ShdrLine.GetNextValue(y);
                            y = ShdrLine.GetNextSegment(y);
                            if (!string.IsNullOrEmpty(x)) condition.NativeSeverity = x;

                            if (y != null)
                            {
                                // Set Qualifier
                                x = ShdrLine.GetNextValue(y);
                                y = ShdrLine.GetNextSegment(y);
                                var qualifier = x.ConvertEnum<ConditionQualifier>();
                                if (qualifier != ConditionQualifier.NOT_SPECIFIED)
                                {
                                    condition.Qualifier = qualifier;
                                }
                            }
                        }

                        // Set Message
                        x = ShdrLine.GetNextValue(y);
                        if (!string.IsNullOrEmpty(x)) condition.Message = x;
                    }

                    return condition;
                }
                catch { }
            }

            return null;
        }
    }
}