// Copyright (c) 2022 TrakHound Inc., All Rights Reserved.

// This file is subject to the terms and conditions defined in
// file 'LICENSE.txt', which is part of this source code package.

using System;

namespace MTConnect.Observations.Input
{
    /// <summary>
    /// An Information Model that describes Condition Streaming Data reported by a piece of equipment.
    /// </summary>
    public class ConditionObservationInput : ObservationInput
    {
        /// <summary>
        /// Level of the Condition (Normal, Warning, Fault, or Unavailable)
        /// </summary>
        public ConditionLevel Level
        {
            get => GetValue(ValueKeys.Level).ConvertEnum<ConditionLevel>();
            set => AddValue(new ObservationValue(ValueKeys.Level, value));
        }

        /// <summary>
        /// The native code (usually an alpha-numeric value) generated by the controller of a piece of equipment providing a reference identifier for a condition state or alarm.
        /// This is the same information an operator or maintenance personnel would see as a reference code designating a specific type of Condition when viewed at the piece of equipment.Usually this reference code is used to point to a more detailed description of the Condition.
        /// </summary>
        public string NativeCode
        {
            get => GetValue(ValueKeys.NativeCode);
            set => AddValue(new ObservationValue(ValueKeys.NativeCode, value));
        }

        /// <summary>
        /// If the data source assigns a severity level to a Condition, nativeSeverity is used to report that severity information to a client software application.
        /// </summary>
        public string NativeSeverity
        {
            get => GetValue(ValueKeys.NativeSeverity);
            set => AddValue(new ObservationValue(ValueKeys.NativeSeverity, value));
        }

        /// <summary>
        /// Qualifies the Condition and adds context or additional clarification.
        /// This optional attribute can be used to convey information such as HIGH or LOW type Warning and Fault condition to indicate differing types of condition states
        /// </summary>
        public ConditionQualifier Qualifier
        {
            get => GetValue(ValueKeys.Qualifier).ConvertEnum<ConditionQualifier>();
            set => AddValue(new ObservationValue(ValueKeys.Qualifier, value));
        }

        /// <summary>
        /// The CDATA of the Condition Observation
        /// </summary>
        public string Text
        {
            get => GetValue(ValueKeys.CDATA);
            set => AddValue(new ObservationValue(ValueKeys.CDATA, value));
        }


        public ConditionObservationInput() { }

        public ConditionObservationInput(string dataItemKey)
        {
            DataItemKey = dataItemKey;
        }

        public ConditionObservationInput(string dataItemKey, ConditionLevel level)
        {
            DataItemKey = dataItemKey;
            Level = level;
        }

        public ConditionObservationInput(string dataItemKey, ConditionLevel level, long timestamp)
        {
            DataItemKey = dataItemKey;
            Level = level;
            Timestamp = timestamp;
        }

        public ConditionObservationInput(string dataItemKey, ConditionLevel level, DateTime timestamp)
        {
            DataItemKey = dataItemKey;
            Level = level;
            Timestamp = timestamp.ToUnixTime();
        }
    }
}