// Copyright (c) 2023 TrakHound Inc., All Rights Reserved.
// TrakHound Inc. licenses this file to you under the MIT license.

using MTConnect.Devices.DataItems.Samples;

namespace MTConnect.Observations.Samples.Values
{
    /// <summary>
    /// The value of Wattage used or generated by a component over an interval of time.
    /// </summary>
    public class ElectricalEnergyValue : SampleValue
    {
        public ElectricalEnergyValue(double nativeValue, string nativeUnits = ElectricalEnergyDataItem.DefaultUnits)
        {
            Value = nativeValue;
            _units = ElectricalEnergyDataItem.DefaultUnits;
            _nativeUnits = nativeUnits;
        }
    }
}