// Copyright (c) 2022 TrakHound Inc., All Rights Reserved.

// This file is subject to the terms and conditions defined in
// file 'LICENSE.txt', which is part of this source code package.

using MTConnect.Streams;
using System;

namespace MTConnect.Observations
{
    /// <summary>
    /// An Information Model that describes Condition Streaming Data reported by a piece of equipment.
    /// </summary>
    public class ConditionObservation : Observation
    {
        /// <summary>
        /// Level of the Condition (Normal, Warning, Fault, or Unavailable)
        /// </summary>
        public ConditionLevel Level
        {
            get => GetValue(ValueTypes.Level).ConvertEnum<ConditionLevel>();
            set => AddValue(new ObservationValue(ValueTypes.Level, value));
        }

        /// <summary>
        /// The native code (usually an alpha-numeric value) generated by the controller of a piece of equipment providing a reference identifier for a condition state or alarm.
        /// This is the same information an operator or maintenance personnel would see as a reference code designating a specific type of Condition when viewed at the piece of equipment.Usually this reference code is used to point to a more detailed description of the Condition.
        /// </summary>
        public string NativeCode
        {
            get => GetValue(ValueTypes.NativeCode);
            set => AddValue(new ObservationValue(ValueTypes.NativeCode, value));
        }

        /// <summary>
        /// If the data source assigns a severity level to a Condition, nativeSeverity is used to report that severity information to a client software application.
        /// </summary>
        public string NativeSeverity
        {
            get => GetValue(ValueTypes.NativeSeverity);
            set => AddValue(new ObservationValue(ValueTypes.NativeSeverity, value));
        }

        /// <summary>
        /// Qualifies the Condition and adds context or additional clarification.
        /// This optional attribute can be used to convey information such as HIGH or LOW type Warning and Fault condition to indicate differing types of condition states
        /// </summary>
        public string Qualifier
        {
            get => GetValue(ValueTypes.Qualifier);
            set => AddValue(new ObservationValue(ValueTypes.Qualifier, value));
        }

        /// <summary>
        /// The CDATA of the Condition Observation
        /// </summary>
        public string Message
        {
            get => GetValue(ValueTypes.CDATA);
            set => AddValue(new ObservationValue(ValueTypes.CDATA, value));
        }


        public ConditionObservation() { }

        public ConditionObservation(string key)
        {
            Key = key;
        }

        public ConditionObservation(string key, ConditionLevel level)
        {
            Key = key;
            Level = level;
        }

        public ConditionObservation(string key, ConditionLevel level, long timestamp)
        {
            Key = key;
            Level = level;
            Timestamp = timestamp;
        }

        public ConditionObservation(string key, ConditionLevel level, DateTime timestamp)
        {
            Key = key;
            Level = level;
            Timestamp = timestamp.ToUnixTime();
        }
    }
}
