import { defineConfig } from 'vitepress';
import { withMermaid } from 'vitepress-plugin-mermaid';

// VitePress config for MTConnect.NET documentation.
//
// Site root: `docs/` (the existing top-level docs directory).
// Mermaid: enabled via `vitepress-plugin-mermaid` so every architecture /
// sequence / class-relationship / state-machine / wire-flow diagram is
// authored in Mermaid (no ASCII art, no external image renders for
// schematic content).

export default withMermaid(
  defineConfig({
    title: 'MTConnect.NET',
    description:
      'The .NET implementation of the MTConnect Standard — 100% public-surface API coverage, 100% MTConnect Standard compliance.',
    lang: 'en-GB',

    // Output directory for `docs:build`. Default is `docs/.vitepress/dist`;
    // overriding here is unnecessary unless we deploy from elsewhere.
    // outDir: '.vitepress/dist',

    // Base path. Defaults to '/'. If GitHub Pages publishes under a project
    // path (e.g. `/MTConnect.NET/`), this will need to be set at deploy
    // time. Left as the default for now.
    // base: '/',

    cleanUrls: true,

    // Some narrative pages cross-link to the generated API reference, which
    // is produced by docfx in CI (`docs/.docfx/docfx.json`) before VitePress
    // builds. The dead-link check is permissive so a local build without the
    // API output still completes; CI runs docfx first so production builds
    // have the full link graph.
    ignoreDeadLinks: true,

    head: [
      ['meta', { name: 'theme-color', content: '#1f6feb' }],
    ],

    themeConfig: {
      // Top nav: Compliance / Configure & Use / API / Concepts / Wire
      // formats / Modules / CLI / Cookbook / Troubleshooting.
      nav: [
        { text: 'Getting started', link: '/getting-started' },
        { text: 'Compliance', link: '/compliance/' },
        { text: 'Configure & Use', link: '/configure/' },
        { text: 'Concepts', link: '/concepts/' },
        { text: 'API', link: '/api/' },
        { text: 'Wire formats', link: '/wire-formats/' },
        { text: 'Modules', link: '/modules/' },
        { text: 'CLI', link: '/cli/' },
        { text: 'Cookbook', link: '/cookbook/' },
        { text: 'Examples', link: '/examples/' },
        { text: 'Troubleshooting', link: '/troubleshooting/' },
      ],

      // Per-section sidebars. The link targets here are the canonical
      // entry points for each section; the API sidebar is generated by
      // docfx and merged in at build time.
      sidebar: {
        '/compliance/': [
          {
            text: 'MTConnect Standard compliance',
            items: [
              { text: 'Overview', link: '/compliance/' },
              { text: 'Per-version compliance matrix', link: '/compliance/per-version-matrix' },
              { text: 'Wire-format compliance', link: '/compliance/wire-format' },
              { text: 'Spec-source-vs-implementation cross-references', link: '/compliance/spec-cross-references' },
              { text: 'Known divergences from the Standard', link: '/compliance/known-divergences' },
              { text: 'Compliance test harness', link: '/compliance/test-harness' },
            ],
          },
        ],
        '/configure/': [
          {
            text: 'Configure & Use',
            items: [
              { text: 'Overview', link: '/configure/' },
              { text: 'Install', link: '/configure/install' },
              { text: 'Agent configuration', link: '/configure/agent-config' },
              { text: 'Adapter configuration', link: '/configure/adapter-config' },
              { text: 'Module configuration', link: '/configure/module-config' },
            ],
          },
          {
            text: 'Integrations',
            items: [
              { text: 'InfluxDB', link: '/configure/integrations/influxdb' },
              { text: 'MQTT — Protocol overview', link: '/configure/integrations/mqtt-protocol' },
              { text: 'MQTT — AWS Greengrass (Moquette)', link: '/configure/integrations/mqtt-aws-greengrass-moquette' },
              { text: 'MQTT — AWS Greengrass (Mqtt-Bridge)', link: '/configure/integrations/mqtt-aws-greengrass-mqtt-bridge' },
              { text: 'MQTT — AWS IoT', link: '/configure/integrations/mqtt-aws-iot' },
              { text: 'MQTT — HiveMQ', link: '/configure/integrations/mqtt-hivemq' },
              { text: 'OpenSSL setup', link: '/configure/integrations/openssl' },
            ],
          },
        ],
        '/concepts/': [
          {
            text: 'Concepts',
            items: [
              { text: 'Overview', link: '/concepts/' },
              { text: 'Devices', link: '/concepts/devices' },
              { text: 'Components', link: '/concepts/components' },
              { text: 'Data items', link: '/concepts/data-items' },
              { text: 'Observations', link: '/concepts/observations' },
              { text: 'Assets', link: '/concepts/assets' },
              { text: 'Relationships', link: '/concepts/relationships' },
            ],
          },
        ],
        '/api/': [
          {
            text: 'API reference',
            items: [{ text: 'Overview', link: '/api/' }],
          },
        ],
        '/wire-formats/': [
          {
            text: 'Wire formats',
            items: [
              { text: 'Overview', link: '/wire-formats/' },
              { text: 'XML', link: '/wire-formats/xml' },
              { text: 'JSON v1', link: '/wire-formats/json-v1' },
              { text: 'JSON-CPPAGENT (v2)', link: '/wire-formats/json-v2-cppagent' },
              { text: 'JSON-CPPAGENT-MQTT', link: '/wire-formats/json-v2-cppagent-mqtt' },
              { text: 'SHDR', link: '/wire-formats/shdr' },
            ],
          },
        ],
        '/modules/': [
          {
            text: 'Modules',
            items: [
              { text: 'Overview', link: '/modules/' },
            ],
          },
          {
            text: 'Agent modules',
            items: [
              { text: 'HTTP server', link: '/modules/http-server' },
              { text: 'MQTT broker', link: '/modules/mqtt-broker' },
              { text: 'MQTT relay', link: '/modules/mqtt-relay' },
              { text: 'MQTT adapter', link: '/modules/mqtt-adapter' },
              { text: 'HTTP adapter', link: '/modules/http-adapter' },
              { text: 'SHDR adapter', link: '/modules/shdr-adapter' },
            ],
          },
          {
            text: 'Adapter modules',
            items: [
              { text: 'SHDR output', link: '/modules/shdr-output' },
              { text: 'MQTT output', link: '/modules/mqtt-output' },
            ],
          },
        ],
        '/cli/': [
          {
            text: 'CLI tools',
            items: [
              { text: 'Overview', link: '/cli/' },
            ],
          },
          {
            text: 'Shipped CLIs',
            items: [
              { text: 'Agent', link: '/cli/agent' },
              { text: 'Adapter', link: '/cli/adapter' },
            ],
          },
          {
            text: 'Contributor CLIs',
            items: [
              { text: 'tools/dotnet.sh', link: '/cli/dotnet-sh' },
              { text: 'tools/test.sh', link: '/cli/test-sh' },
              { text: 'SysML importer', link: '/cli/sysml-import' },
              { text: 'Release builder', link: '/development/builder' },
            ],
          },
        ],
        '/examples/': [
          {
            text: 'Examples',
            items: [
              { text: 'Overview', link: '/examples/' },
              { text: 'Embedded agent', link: '/examples/agent-embedded' },
              { text: 'HTTP client', link: '/examples/client-http' },
              { text: 'MQTT client', link: '/examples/client-mqtt' },
              { text: 'SHDR client', link: '/examples/client-shdr' },
            ],
          },
        ],
        '/development/': [
          {
            text: 'Repository development',
            items: [
              { text: 'Release builder', link: '/development/builder' },
            ],
          },
        ],
        '/cookbook/': [
          {
            text: 'Cookbook',
            items: [
              { text: 'Overview', link: '/cookbook/' },
              { text: 'Write an agent', link: '/cookbook/write-an-agent' },
              { text: 'Write an adapter', link: '/cookbook/write-an-adapter' },
              { text: 'Write a module', link: '/cookbook/write-a-module' },
              { text: 'Configure the MQTT relay', link: '/cookbook/configure-mqtt-relay' },
              { text: 'Write a JSON-MQTT consumer', link: '/cookbook/write-a-json-mqtt-consumer' },
              { text: 'Migrate between versions', link: '/cookbook/migrate-versions' },
            ],
          },
        ],
        '/troubleshooting/': [
          {
            text: 'Troubleshooting',
            items: [
              { text: 'Overview', link: '/troubleshooting/' },
              { text: 'Common error modes', link: '/troubleshooting/common-error-modes' },
              { text: 'XSD validation failures', link: '/troubleshooting/xsd-validation-failures' },
              { text: 'Schema version mismatches', link: '/troubleshooting/schema-version-mismatches' },
              { text: 'MQTT TLS handshake', link: '/troubleshooting/mqtt-tls-handshake' },
            ],
          },
        ],
      },

      socialLinks: [
        { icon: 'github', link: 'https://github.com/TrakHound/MTConnect.NET' },
      ],

      footer: {
        message: 'Released under the MIT License.',
        copyright: 'Copyright © TrakHound Inc.',
      },

      search: {
        provider: 'local',
      },
    },

    // Mermaid plugin options — leave at sensible defaults so diagrams pick
    // up the site's light/dark theme automatically.
    mermaid: {
      // example: securityLevel: 'loose',
    },
    mermaidPlugin: {
      class: 'mermaid my-mermaid',
    },
  })
);
