// Copyright (c) 2026 TrakHound Inc., All Rights Reserved.
// TrakHound Inc. licenses this file to you under the MIT license.

using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using MTConnect.Agents;
using MTConnect.Devices;
using MTConnect.Devices.Json;
using NUnit.Framework;

namespace MTConnect.Tests.JsonCppagent.Devices
{
    /// <summary>
    /// End-to-end wire-shape pin: builds an MTConnect agent broker (which
    /// initialises the synthetic Agent device), adds two production-shaped
    /// devices, calls <c>GetDevicesResponseDocument</c> through the same
    /// public surface an HTTP /probe handler uses, runs the result through
    /// <c>JsonDevicesResponseDocument</c> (the cppagent-format Probe
    /// serialiser the JSON-CPPAGENT-MQTT module also feeds), and asserts the
    /// emitted JSON contains exactly one <c>ASSET_COUNT</c> DataItem per
    /// device with <c>representation: "DATA_SET"</c>.
    ///
    /// The pin closes the gap left by
    /// <c>AssetCountAutoGeneratedDataSetTests</c> (which only exercises the
    /// in-memory ctor stamping) and <c>AssetCountFactoryDataSetGuardTests</c>
    /// (which only exercises the factory-side guard). Neither of those
    /// exercises the full agent → JSON-cppagent serialiser chain, so a
    /// downstream consumer's report of a third <c>ASSET_COUNT</c>
    /// DataItem with <c>representation=VALUE</c> on the wire could
    /// not previously be caught by the test suite.
    ///
    /// Source authority:
    /// - SysML XMI: <c>AssetCount</c> EventEnum element ID
    ///   <c>_19_0_3_68e0225_1640602520420_217627_44</c>. <c>result</c>
    ///   is declared with structured-representation prose (DATA_SET) per
    ///   the EventEnum literal's description.
    /// - Generated source: <c>libraries/MTConnect.NET-Common/Devices/DataItems/AssetCountDataItem.g.cs</c>
    ///   declares <c>DefaultRepresentation = DataItemRepresentation.DATA_SET</c>;
    ///   both ctors stamp <c>Representation = DefaultRepresentation</c>.
    /// - Two known agent-side emission paths:
    ///   <c>libraries/MTConnect.NET-Common/Devices/Agent.cs:90</c> (Agent
    ///   device's own InitializeDataItems) and
    ///   <c>libraries/MTConnect.NET-Common/Agents/MTConnectAgent.cs:1170</c>
    ///   (NormalizeDeviceRequiredDataItems for any added device). Both go
    ///   through the AssetCountDataItem ctor.
    /// - JSON-cppagent serialisation: <c>JsonDataItem.cs</c> emits the
    ///   <c>representation</c> JSON field only when the DataItem's
    ///   Representation is NOT VALUE (so a VALUE entry on the wire shows
    ///   up as "no representation key" rather than as
    ///   <c>representation: "VALUE"</c>).
    /// </summary>
    [TestFixture]
    [Category("AssetCountIsDataSet")]
    public class AssetCountWireRepresentationE2ETests
    {
        [Test]
        public void Probe_response_emits_exactly_one_ASSET_COUNT_per_device_with_DATA_SET_representation()
        {
            using var agent = new MTConnectAgentBroker();

            var device1 = new Device
            {
                Id = "f1",
                Uuid = "f1-uuid",
                Name = "Furnace1"
            };
            var device2 = new Device
            {
                Id = "f2",
                Uuid = "f2-uuid",
                Name = "Furnace2"
            };
            agent.AddDevice(device1);
            agent.AddDevice(device2);

            var document = agent.GetDevicesResponseDocument();
            Assert.That(document, Is.Not.Null);
            Assert.That(document.Devices, Is.Not.Null);

            var json = MTConnect.JsonFunctions.Convert(new JsonDevicesResponseDocument(document));
            Assert.That(json, Is.Not.Null);

            using var doc = JsonDocument.Parse(json!);

            // Walk the entire response document and collect every DataItem
            // whose type is ASSET_COUNT, grouped by the device-uuid that
            // owns it. Walking the whole tree (vs hard-coding paths) means
            // a regression that injects an ASSET_COUNT in an unexpected place
            // (e.g. inside a Component's DataItems collection) is caught by
            // the per-device cardinality assertion below. The cppagent JSON
            // shape splits the Devices container into two arrays: `Agent`
            // (the synthetic agent device) and `Device` (production devices)
            // — both must be visited.
            var assetCountsByDeviceUuid = new Dictionary<string, List<JsonElement>>();
            var devicesContainer = doc.RootElement
                .GetProperty("MTConnectDevices")
                .GetProperty("Devices");
            foreach (var arrayName in new[] { "Agent", "Device" })
            {
                if (!devicesContainer.TryGetProperty(arrayName, out var arrayElement))
                    continue;
                foreach (var device in arrayElement.EnumerateArray())
                {
                    var uuid = device.GetProperty("uuid").GetString() ?? "(no-uuid)";
                    var collected = new List<JsonElement>();
                    CollectAssetCountDataItems(device, collected);
                    assetCountsByDeviceUuid[uuid] = collected;
                }
            }

            // Every device in the response — the synthetic Agent device
            // plus the two production-shaped devices — must carry exactly
            // ONE ASSET_COUNT DataItem.
            foreach (var (uuid, items) in assetCountsByDeviceUuid)
            {
                Assert.That(items.Count, Is.EqualTo(1),
                    $"Device uuid='{uuid}' has {items.Count} ASSET_COUNT DataItems on the wire; expected exactly 1.");
            }

            // Every ASSET_COUNT DataItem on the wire must carry an
            // explicit representation: "DATA_SET" key. Per the
            // JsonDataItem serializer's omit-on-VALUE rule, the absence
            // of the key would mean Representation=VALUE — the wire
            // regression a downstream consumer would observe.
            foreach (var (uuid, items) in assetCountsByDeviceUuid)
            {
                var item = items[0];
                Assert.That(item.TryGetProperty("representation", out var representation), Is.True,
                    $"Device uuid='{uuid}' ASSET_COUNT has no `representation` key (would default to VALUE on consumer round-trip).");
                Assert.That(representation.GetString(), Is.EqualTo("DATA_SET"),
                    $"Device uuid='{uuid}' ASSET_COUNT representation is not DATA_SET.");
            }
        }

        [Test]
        public void Probe_response_for_agent_device_emits_exactly_one_ASSET_COUNT_with_DATA_SET()
        {
            // The agent device specifically exercises Agent.cs:90's
            // InitializeDataItems path, which is the second of the two
            // ctor-stamping paths (the other is
            // MTConnectAgent.NormalizeDeviceRequiredDataItems for any added
            // device). This test pins the agent-device branch in isolation
            // — even with no production-shaped devices added — so a regression
            // that breaks Agent.InitializeDataItems' ASSET_COUNT stamping
            // surfaces here without being masked by other devices.
            using var agent = new MTConnectAgentBroker();

            var document = agent.GetDevicesResponseDocument();
            Assert.That(document, Is.Not.Null);
            Assert.That(document.Devices, Is.Not.Null);
            Assert.That(document.Devices.Any(d => d.Type == Agent.TypeId), Is.True,
                "Expected the synthetic Agent device to be present in the probe response.");

            var json = MTConnect.JsonFunctions.Convert(new JsonDevicesResponseDocument(document));
            using var doc = JsonDocument.Parse(json!);

            // The cppagent JSON shape places the synthetic Agent device
            // under `Devices.Agent[]` (not `Devices.Device[]` — that's
            // for production devices). Read the agent device from there.
            var devicesContainer = doc.RootElement
                .GetProperty("MTConnectDevices")
                .GetProperty("Devices");
            Assert.That(devicesContainer.TryGetProperty("Agent", out var agentArray), Is.True,
                "Probe response has no `MTConnectDevices.Devices.Agent` array — the synthetic Agent device should always appear there.");
            Assert.That(agentArray.GetArrayLength(), Is.EqualTo(1),
                $"Expected exactly one synthetic Agent device, got {agentArray.GetArrayLength()}.");
            var agentDevice = agentArray[0];

            var agentAssetCounts = new List<JsonElement>();
            CollectAssetCountDataItems(agentDevice, agentAssetCounts);

            Assert.That(agentAssetCounts.Count, Is.EqualTo(1),
                $"Agent device emits {agentAssetCounts.Count} ASSET_COUNT DataItems on the wire; expected exactly 1. A third entry with representation=VALUE is the regression this pin guards against.");

            var item = agentAssetCounts[0];
            Assert.That(item.TryGetProperty("representation", out var representation), Is.True,
                "Agent device ASSET_COUNT has no `representation` key on the wire (would default to VALUE on consumer round-trip).");
            Assert.That(representation.GetString(), Is.EqualTo("DATA_SET"),
                "Agent device ASSET_COUNT representation is not DATA_SET on the wire.");
        }

        [Test]
        public void Probe_response_string_carries_no_VALUE_representation_on_any_ASSET_COUNT_entry()
        {
            // Belt-and-braces sanity check on the raw JSON string. The
            // JsonDataItem serialiser is configured to OMIT the `representation`
            // key when the in-memory Representation == VALUE; an explicit
            // `"representation":"VALUE"` substring next to an ASSET_COUNT
            // entry would therefore signal a serialiser-side bug (a code
            // path that explicitly emits the literal "VALUE" rather than
            // honoring the omit-on-VALUE rule). This pin catches that
            // specific shape regardless of where in the document tree the
            // offending entry sits.
            using var agent = new MTConnectAgentBroker();
            agent.AddDevice(new Device { Id = "f1", Uuid = "f1-uuid", Name = "Furnace1" });

            var json = MTConnect.JsonFunctions.Convert(
                new JsonDevicesResponseDocument(agent.GetDevicesResponseDocument()))!;

            // Naive but precise: search for the literal pair surrounded by
            // commas. False-positives are not possible — `representation` is
            // a JSON property name only used on DataItem entries, and the
            // only legal values are the four representation enum strings;
            // a `"VALUE"` value next to an ASSET_COUNT type would have to
            // come from a serialiser bug.
            using var doc = JsonDocument.Parse(json);
            var assetCounts = new List<JsonElement>();
            var devicesContainer = doc.RootElement
                .GetProperty("MTConnectDevices")
                .GetProperty("Devices");
            foreach (var arrayName in new[] { "Agent", "Device" })
            {
                if (!devicesContainer.TryGetProperty(arrayName, out var arrayElement))
                    continue;
                foreach (var device in arrayElement.EnumerateArray())
                {
                    CollectAssetCountDataItems(device, assetCounts);
                }
            }
            foreach (var item in assetCounts)
            {
                if (item.TryGetProperty("representation", out var representation))
                {
                    Assert.That(representation.GetString(), Is.Not.EqualTo("VALUE"),
                        "An ASSET_COUNT DataItem on the wire carries `representation: \"VALUE\"` — the serialiser should have omitted the key (the omit-on-VALUE rule) or the producer should have stamped DATA_SET. Either way, this is a regression.");
                }
            }
        }

        // Recursive walk over a Device or Component subtree, collecting every
        // DataItem whose type is "ASSET_COUNT". Handles the cppagent JSON
        // shape's wrapping conventions (DataItems.DataItem[] arrays,
        // Components.<TypeName>[] arrays, Compositions.Composition[] arrays)
        // and the "object instead of single-element array" sugar that the
        // serialiser sometimes emits.
        private static void CollectAssetCountDataItems(JsonElement node, List<JsonElement> sink)
        {
            if (node.TryGetProperty("DataItems", out var dataItemsContainer)
                && dataItemsContainer.TryGetProperty("DataItem", out var dataItemArray))
            {
                IEnumerable<JsonElement> items = dataItemArray.ValueKind == JsonValueKind.Array
                    ? dataItemArray.EnumerateArray()
                    : new[] { dataItemArray };
                foreach (var di in items)
                {
                    if (di.TryGetProperty("type", out var typeElement)
                        && typeElement.GetString() == "ASSET_COUNT")
                    {
                        sink.Add(di);
                    }
                }
            }

            if (node.TryGetProperty("Components", out var componentsContainer))
            {
                foreach (var componentTypeProperty in componentsContainer.EnumerateObject())
                {
                    var componentArray = componentTypeProperty.Value;
                    IEnumerable<JsonElement> children = componentArray.ValueKind == JsonValueKind.Array
                        ? componentArray.EnumerateArray()
                        : new[] { componentArray };
                    foreach (var child in children)
                    {
                        CollectAssetCountDataItems(child, sink);
                    }
                }
            }
        }
    }
}
